### PR TITLE
Added Linux and CMake support to make building easier.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
The changes I made were assorted, but the list I gave in my comment on reddit was the most of it.

1. The code used for each which is a MSVC extension to do looping, for (type name : list) is a portable way of doing for each loops in C++.
2. The dependency of Xinput is a non-starter on linux. I replaced the functions with functions that always return the error value so that it would compile, but unless there is a rewrite accessing <linux/joystick.h> or something, controllers aren't going to work on linux.
3. There was a explicitly called parent destructor in VCollision.h which you can't do without passing in this. Either way, because the destructor is virtual it gets called automatically.
4. Headers were all done in a Windows-only way #include <blah\blah> as opposed to the cross-platform way #include <blah/blah>. Additionally there were some missing standard headers.

### CODE REVIEW

**Comment by gamepopper** [comment]
All looks good to me.

**Comment by gamepopper** [comment]
Gonna add _sfml-main.lib_ to the linker as (for windows at least) it's needed to use the regular main function instead of the windows function when building a Win32 application.

Not doing so would produce a link error, which was why this code below was in the original main function.

```

#if defined(_WIN32)
#include <windows.h>

extern int main();
INT WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, INT)
{
	return main();
}
#endif
```

**Comment by gamepopper** [comment]
Also, I currently use Visual Studio 2013, but this pull was compiled with 2015. Should probably upgrade, but maybe alternatively could remove the visual studio solutions so CMake could build them instead.

**Comment by cwfitzgerald** [comment]
I haven't actually used SFML at all (I have always used SDL2) but both of them have weird linker issues because they both replace main with their own stuff. 

Visual Studio 2017 and up have a cmake feature where you open the folder that the cmake files are in and it uses cmake to generate projects automatically. It's actually pretty awesome.

**Comment by gamepopper** [comment]
Tried out the CMake file in Linux, might be because I'm compiling my own SFML instead but when I try to set the include directory to where I've placed it, it cannot find the library files.

EDIT: Got it to find SFML, now it's having problems finding the OGG and Vorbis lib files.

**Comment by cwfitzgerald** [comment]
If you're on ubuntu/debian do `sudo apt install libogg-dev libvorbis-dev` and that should pull in all of your dependencies for you.

**Comment by gamepopper** [comment]
Yeah Linux ended up being much more easier to sort out after setting SFML_ROOT and renaming the findOGG and findVORBIS to work.

CMake on Windows, on the otherhand just doesn't like how I organise my libraries...

**Comment by cwfitzgerald** [comment]
cmake is identical on all platforms. Whatever you set CMAKE_PREFIX_PATH to it will look inside CMAKE_PREFIX_PATH/bin for any executables, CMAKE_PREFIX_PATH/include for include files, and CMAKE_PREFIX_PATH/lib for all libraries to link against. Once you have that down, dealing with cmake is really easy and portable. You just have to build up a collection of different libraries and stuff.

On Debian for example CMAKE_PREFIX_PATH could be /usr/ as that has everything you need.

**Comment by gamepopper** [comment]
Ah okay, now it's just missing the include directories...
Hate the idea of having to reorganise my libraries again but I'm getting the hang of this.

**Comment by cwfitzgerald** [comment]
Trust me, I hated having to deal with cmake at first, but once you get into the swing of things, it makes life so much easier. You can compile a whole load of stuff without second thought. I found [this](https://github.com/CellCognition/cecog/wiki/Windows-x64-(MSVS-2013)-source-installation-guide) page not too long ago which saved my ass, having a download with precompiled 64bit versions of a bunch of basic libraries for windows when I couldn't easily find them. It is the only reason I have a 64bit libpng.

**Pull request merged**
